### PR TITLE
fixes

### LINKED ISSUE #1043: sysaudio: `floatToSigned` panics when passing samples outside range [-1,1]
Hi, I've found some issues on windows using sysaudio, this particular one panics the application because a `1.001` float overflows an `i16`, do you say that's a check that should be done in the application? The in-famous audio clippinng would be trivial to implement both in the `.write(channel, sample)` function and on each project using sysaudio.. in any case, debugging this issue required a ton of work because windows doesn't provide stack traces unless you use a debugger, and if clipping is at the end of the day necessary, we could handle it on the library to prevent the zig panic.

https://github.com/menduz/mach-sysaudio/commit/f1a42f7fecdf07a51b84feb2f8a692dc3cf54b0c

~Maybe this is an underlying issue, but even though we ask for a `format=f32` player, the wasapi is still creating a `i16` one.~ This is confirmed not an issue, in my windows setup there are only `i16` devices.

If you are interested in my solution, I've fixed the issue using the [std.math.tanh(sample)](https://www.mathworks.com/help/matlab/ref/tanh.html) function to ensure a soft-clipping and to enable adding channels as much as needed. Here is an interesting link where I took a lot of information from https://stackoverflow.com/questions/50436323/what-is-correct-way-to-add-audio-samples-into-the-one-without-clipping.

### PR DESCRIPTION
**Pull request by alichraghi**
Closes https://github.com/hexops/mach/issues/1043

- [x] By selecting this checkbox, I agree to license my contributions to this project under the license(s) described in the LICENSE file, and I have the right to do so or have received permission to do so by an employer or client I am producing work for whom has this right.

### CODE REVIEW

File: examples/record.zig [hunk 1]
```diff
@@ -44,20 +44,18 @@ pub fn main() !void {
...
-            _ = bw.write(&sample_bytes) catch {};
-        }
-    }
-    bw.flush() catch {};
+fn readCallback(_: ?*anyopaque, input: []const u8) void {
+    const format_size = recorder.format().size();
+    const frames = input.len / format_size;
+
+    var buffer: [16 * 1024]f32 = undefined;
+    recorder.read(f32, buffer[0..frames], input);
```
Comment (emidoots) [inline examples/record.zig]: Is there any reason that `recorder.read` (and `.write`) need to be methods? This API design feels very strange:

* Your `readCallback` is called with the `input` from the microphone
* You then need to ask the `recorder` to `read` data, ??? what does that even mean, weren't we given it as `input`?

I think `sysaudio.convert` would probably be a better way to phrase `read`, I have some more thoughts I'll type up.

Comment (emidoots) [reply examples/record.zig]: My thoughts: https://github.com/hexops/mach/issues/1099

**Review by emidoots — APPROVED** [review]
This looks like a step in the right direction, so will merge.

I'd like to see us land somewhere like what I described in https://github.com/hexops/mach/issues/1099

After that, we can start updating mach-flac and mach-opus examples

**Comment by emidoots** [comment]
image

Windows build is broken so I can't merge

File: examples/record.zig (hunk 1 above)
Comment (alichraghi) [reply examples/record.zig]: fair enough. the name is indeed confusing. but we can't make convert them into a single `convert` function because it requires unneeded ugly casts as both `input` and `output` has to be `u8` slices.
